name = "glas"
main = "_worker.js"
compatibility_date = "2025-03-29"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "."

[vars]
GITHUB_REPO = "filippo-transmediale/glas"

[[routes]]
pattern = "glas.works"
custom_domain = true
